version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-user
    environment:
      POSTGRES_USER: supplies
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_supplies
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: